"""remove idempotency_key unique constraint

Revision ID: 18e911d594a2
Revises: dfa134d05d4b
Create Date: 2026-08-17 17:27:10.313629

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "18e911d594a2"
down_revision: str | Sequence[str] | None = "dfa134d05d4b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("payments_idempotency_key_key"), "payments", type_="unique")
    op.create_unique_constraint(
        "uq_payment_order_idempotency_key", "payments", ["order_id", "idempotency_key"]
    )
    op.create_check_constraint("ck_payment_amount_positive", "payments", "amount > 0")
    op.create_check_constraint("ck_product_price_positive", "products", "price > 0")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_product_price_positive", "products", type_="check")
    op.drop_constraint("ck_payment_amount_positive", "payments", type_="check")
    op.drop_constraint("uq_payment_order_idempotency_key", "payments", type_="unique")
    op.create_unique_constraint(
        op.f("payments_idempotency_key_key"),
        "payments",
        ["idempotency_key"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
