"""update order defaults and constraints

Revision ID: 6982fe26ad88
Revises: 9cd6aea592cc
Create Date: 2024-08-14 10:27:53.668956

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "6982fe26ad88"
down_revision: Union[str, Sequence[str], None] = "9cd6aea592cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_order_subtotal_positive"), "orders", type_="check")
    op.drop_constraint(op.f("ck_order_total_positive"), "orders", type_="check")
    op.create_check_constraint(
        "ck_order_discount_non_negative", "orders", "discount >= 0"
    )
    op.create_check_constraint(
        "ck_order_shipping_non_negative", "orders", "shipping >= 0"
    )
    op.create_check_constraint(
        "ck_order_subtotal_non_negative", "orders", "subtotal >= 0"
    )
    op.create_check_constraint("ck_order_tax_non_negative", "orders", "tax >= 0")
    op.create_check_constraint("ck_order_total_non_negative", "orders", "total >= 0")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_order_total_non_negative", "orders", type_="check")
    op.drop_constraint("ck_order_tax_non_negative", "orders", type_="check")
    op.drop_constraint("ck_order_subtotal_non_negative", "orders", type_="check")
    op.drop_constraint("ck_order_shipping_non_negative", "orders", type_="check")
    op.drop_constraint("ck_order_discount_non_negative", "orders", type_="check")
    op.create_check_constraint(
        op.f("ck_order_total_positive"), "orders", "total > 0::numeric"
    )
    op.create_check_constraint(
        op.f("ck_order_subtotal_positive"), "orders", "subtotal > 0::numeric"
    )
    # ### end Alembic commands ###
