"""add unique constraint to order items

Revision ID: 87257f9cd11f
Revises: b58eeac0e8b1
Create Date: 2026-08-17 13:00:30.187098

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "87257f9cd11f"
down_revision: str | Sequence[str] | None = "b58eeac0e8b1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_order_item_order_product", "order_items", ["order_id", "product_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_order_item_order_product", "order_items", type_="unique")
    # ### end Alembic commands ###
