"""add email to order

Revision ID: b58eeac0e8b1
Revises: 6982fe26ad88
Create Date: 2024-08-14 12:53:22.506955

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b58eeac0e8b1"
down_revision: str | Sequence[str] | None = "6982fe26ad88"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column(
            "email",
            sa.String(length=255),
            nullable=True,
        ),
    )

    op.execute("UPDATE orders SET email = 'test@example.com' WHERE email IS NULL")

    op.alter_column(
        "orders",
        "email",
        existing_type=sa.String(length=255),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "email")
    # ### end Alembic commands ###
