"""add payment processing timestamp

Revision ID: cb16e1182ad7
Revises: 1eaeb9d8824d
Create Date: 2026-08-19 16:06:10.817054

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cb16e1182ad7"
down_revision: str | Sequence[str] | None = "1eaeb9d8824d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payments",
        sa.Column("processing_started_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payments", "processing_started_at")
    # ### end Alembic commands ###
