"""add order_items product_id index

Revision ID: f76bb6ee06f7
Revises: 87257f9cd11f
Create Date: 2026-08-17 13:24:51.048447

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "f76bb6ee06f7"
down_revision: str | Sequence[str] | None = "87257f9cd11f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
