from decimal import Decimal


PRODUCTS = [
    {
        "name": "Mechanical Keyboard",
        "description": "Mechanical keyboard with RGB backlight",
        "price": Decimal("89.99"),
        "stock": 50,
        "sales_weight": 8,
    },
    {
        "name": "Wireless Mechanical Keyboard",
        "description": "Wireless mechanical keyboard with rechargeable battery",
        "price": Decimal("119.99"),
        "stock": 40,
        "sales_weight": 6,
    },
    {
        "name": "Compact Mechanical Keyboard",
        "description": "Compact 75% mechanical keyboard",
        "price": Decimal("79.99"),
        "stock": 60,
        "sales_weight": 5,
    },
    {
        "name": "Gaming Keyboard",
        "description": "RGB gaming keyboard with programmable keys",
        "price": Decimal("99.99"),
        "stock": 45,
        "sales_weight": 5,
    },
    {
        "name": "Wireless Mouse",
        "description": "Ergonomic wireless mouse",
        "price": Decimal("29.99"),
        "stock": 100,
        "sales_weight": 10,
    },
    {
        "name": "Gaming Mouse",
        "description": "High precision gaming mouse",
        "price": Decimal("49.99"),
        "stock": 80,
        "sales_weight": 8,
    },
    {
        "name": "Ergonomic Mouse",
        "description": "Vertical ergonomic wireless mouse",
        "price": Decimal("44.99"),
        "stock": 70,
        "sales_weight": 6,
    },
    {
        "name": "Bluetooth Mouse",
        "description": "Compact Bluetooth mouse",
        "price": Decimal("24.99"),
        "stock": 120,
        "sales_weight": 7,
    },
    {
        "name": "24-inch Monitor",
        "description": "24-inch Full HD monitor",
        "price": Decimal("149.99"),
        "stock": 35,
        "sales_weight": 4,
    },
    {
        "name": "27-inch Monitor",
        "description": "27-inch Full HD IPS monitor",
        "price": Decimal("219.99"),
        "stock": 30,
        "sales_weight": 4,
    },
    {
        "name": "27-inch 144Hz Monitor",
        "description": "27-inch QHD gaming monitor with 144Hz refresh rate",
        "price": Decimal("299.99"),
        "stock": 25,
        "sales_weight": 3,
    },
    {
        "name": "32-inch 4K Monitor",
        "description": "32-inch 4K UHD professional monitor",
        "price": Decimal("449.99"),
        "stock": 20,
        "sales_weight": 2,
    },
    {
        "name": "Ultrawide Monitor",
        "description": "34-inch ultrawide productivity monitor",
        "price": Decimal("599.99"),
        "stock": 15,
        "sales_weight": 1,
    },
    {
        "name": "Wireless Headphones",
        "description": "Noise-cancelling wireless headphones",
        "price": Decimal("129.99"),
        "stock": 40,
        "sales_weight": 6,
    },
    {
        "name": "Gaming Headset",
        "description": "Surround sound gaming headset with microphone",
        "price": Decimal("89.99"),
        "stock": 50,
        "sales_weight": 7,
    },
    {
        "name": "Bluetooth Earbuds",
        "description": "True wireless Bluetooth earbuds",
        "price": Decimal("69.99"),
        "stock": 80,
        "sales_weight": 8,
    },
    {
        "name": "Studio Headphones",
        "description": "Professional over-ear studio headphones",
        "price": Decimal("179.99"),
        "stock": 25,
        "sales_weight": 2,
    },
    {
        "name": "USB-C Hub",
        "description": "7-in-1 USB-C hub with HDMI and USB ports",
        "price": Decimal("39.99"),
        "stock": 90,
        "sales_weight": 9,
    },
    {
        "name": "USB-C Cable",
        "description": "Braided USB-C charging and data cable",
        "price": Decimal("14.99"),
        "stock": 200,
        "sales_weight": 10,
    },
    {
        "name": "HDMI Cable",
        "description": "High-speed HDMI 2.1 cable",
        "price": Decimal("19.99"),
        "stock": 150,
        "sales_weight": 8,
    },
    {
        "name": "Laptop Stand",
        "description": "Adjustable aluminum laptop stand",
        "price": Decimal("49.99"),
        "stock": 70,
        "sales_weight": 5,
    },
    {
        "name": "Desk Mat",
        "description": "Large waterproof desk mat",
        "price": Decimal("24.99"),
        "stock": 100,
        "sales_weight": 7,
    },
    {
        "name": "Webcam",
        "description": "Full HD USB webcam with built-in microphone",
        "price": Decimal("59.99"),
        "stock": 60,
        "sales_weight": 6,
    },
    {
        "name": "USB Microphone",
        "description": "USB condenser microphone for streaming and calls",
        "price": Decimal("99.99"),
        "stock": 40,
        "sales_weight": 4,
    },
    {
        "name": "External SSD",
        "description": "1TB portable external SSD",
        "price": Decimal("99.99"),
        "stock": 50,
        "sales_weight": 5,
    },
    {
        "name": "External Hard Drive",
        "description": "2TB portable external hard drive",
        "price": Decimal("79.99"),
        "stock": 45,
        "sales_weight": 3,
    },
    {
        "name": "Laptop Backpack",
        "description": "Water-resistant laptop backpack",
        "price": Decimal("64.99"),
        "stock": 60,
        "sales_weight": 5,
    },
    {
        "name": "Power Bank",
        "description": "20,000mAh USB-C power bank",
        "price": Decimal("39.99"),
        "stock": 90,
        "sales_weight": 7,
    },
    {
        "name": "Wireless Charger",
        "description": "Fast wireless charging pad",
        "price": Decimal("29.99"),
        "stock": 100,
        "sales_weight": 8,
    },
    {
        "name": "Desk Lamp",
        "description": "Adjustable LED desk lamp",
        "price": Decimal("34.99"),
        "stock": 75,
        "sales_weight": 4,
    },
]